volumes:
  mongo_data:

services:

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    ports:
      - "27020:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  backend_portfolio:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./portifolio/api:/app
    command: sh -c "npm install && node index.js"
    ports:
      - "3846:3846"
    environment:
      - MONGO_URI=mongodb://mongo:27017/atividade
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy

  backend_gepeto:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./portifolio/api2:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "3847:3847"
    environment:
      - MONGO_URI=mongodb://mongo:27017/gepeto
      - GEPETO_API_AUTH_TOKEN=${GEPETO_API_AUTH_TOKEN}
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy

  backend_login:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./logincomauth/logincomauth/apis:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "7777:7777"
    environment:
      - MONGO_URI=mongodb://mongo:27017/login
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy